name: Pull Requests

on:
  pull_request:

permissions:
  actions: write
  packages: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: Ilyes512/github-actions/.github/workflows/build-php.yml@0.3.0
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        docker:
          - dockerfile: fpm/Dockerfile
            image-name: ghcr.io/${{ github.repository }}
            key: fpm
          - dockerfile: apache/Dockerfile
            image-name: ghcr.io/${{ github.repository }}/apache
            key: apache
    with:
      runner-os: ubuntu-22.04
      platform: ${{ matrix.platform }}
      image-name: ${{ matrix.docker.image-name }}
      dockerfile: ${{ matrix.docker.dockerfile }}
      cache-key: ${{ matrix.os }}-buildx-${{ matrix.platform }}-${{ matrix.docker.key }}-pr-${{ github.event.number }}-${{ github.sha }}
      cache-restore-keys: |
        ${{ matrix.os }}-buildx-${{ matrix.platform }}-${{ matrix.docker.key }}-pr-${{ github.event.number }}-
        ${{ matrix.os }}-buildx-${{ matrix.platform }}-${{ matrix.docker.key }}-pr-
        ${{ matrix.os }}-buildx-${{ matrix.platform }}-${{ matrix.docker.key }}-main-

  merge:
    uses: Ilyes512/github-actions/.github/workflows/merge-php.yml@0.3.0
    needs: build
    strategy:
      matrix:
        image-name:
          - ghcr.io/${{ github.repository }}
          - ghcr.io/${{ github.repository }}/apache
    with:
      runner-os: ubuntu-22.04
      image-name: ${{ matrix.image-name }}
